### ISSUE TITLE
Cannot Add S3 Triggers to Lambda

### ISSUE THREAD

**Issue by omersi** [aws/serverless-application-model#2113]
### Description:
I had a long session with a support team representative who asked me to open a new issue, which relates to https://github.com/aws/serverless-application-model/issues/300

I need my lambda to be triggered by `s3:ObjectCreated:Put` event. 
I could get the function created, but the triggers weren't.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template to deploy lambda functions

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    

# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-s3.html

Resources:
  MyTestingFunctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my_testing_function_sam
      CodeUri: my_code_path/
      Handler: app.lambda_handler
      PackageType: Zip
      DeploymentPreference: 
        Type: Canary10Percent10Minutes
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: files/

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt MyTestingFunctionFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !GetAtt Bucket1.Arn
  
  Bucket1:
    Type: 'AWS::S3::Bucket'
    proerties:
      BucketName: myBucket
```

In this [tutorial](https://medium.com/build-succeeded/subscribe-an-aws-lambda-function-to-an-s3-bucket-event-using-cloudformation-and-sam-80f979675f96), the composer is able to create a trigger, BUT, he's monitoring the same bucket that SAM uses for storing the deployment package.

### Steps to reproduce:
1. Run `sam build`
2. Run `sam deploy`
3. Check the lambda configuration and you'll see that the function was created without the triggers.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu Linux 20.04
2. SAM CLI version: 1.27.2
3. AWS region: us-east-1

**Comment by jfuss** [comment]
For S3, the "triggers" are not on lambda (`aws lambda list-function-event-invoke-configs`) but is viewed on the S3 bucket itself (`aws s3api get-bucket-notification-configuration`).

I deployed this app (which is a fully working version of the above)
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template to deploy lambda functions

Globals:
  Function:
    Timeout: 300
    MemorySize: 512

Resources:
  MyTestingFunctionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my_testing_function_sam
      CodeUri: hello_world/
      Handler: app.lambda_handler
      PackageType: Zip
      Runtime: python3.8
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: files/
  
  Bucket1:
    Type: 'AWS::S3::Bucket'
    proerties:
      BucketName: myBucket
```

This created the bucket notifications which are found on S3:
```
aws s3api get-bucket-notification-configuration --bucket testing-2113-bucket1-6jkpzi9ixg01
{
    "LambdaFunctionConfigurations": [
        {
            "Id": "d0f4d80c-c9a4-48c5-9e5f-bd26ce2a5ab2",
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:007174592951:function:my_testing_function_sam",
            "Events": [
                "s3:ObjectCreated:Put"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "files/"
                        }
                    ]
                }
            }
        }
    ]
}
```

Are you not seeing the configuration on your bucket?

**Comment by omersi** [comment]
I executed the code as you wrote it but the trigger is still missing.

I think it has to do with having another notification over the same bucket for a different path. 

```
aws s3api get-bucket-notification-configuration --bucket my-testing-bucket                 

{
    "LambdaFunctionConfigurations": [
        {
            "Id": "customer-data-stg-fhr-menlo_to_journal",
            "LambdaFunctionArn": "arn:aws:lambda:us-east-1:99xxxxxxxxxx:function:s3_old_function",
            "Events": [
                "s3:ObjectCreated:*"
            ],
            "Filter": {
                "Key": {
                    "FilterRules": [
                        {
                            "Name": "Prefix",
                            "Value": "site/unit/"
                        }
                    ]
                }
            }
        }
    ]
}
```

**Comment by jfuss** [comment]
@omersi I really not following. Is `--bucket my-testing-bucket` in your stack you deployed from my example above? It seems like you are doing something different but I don't have enough information to know what you are doing differnt. Are you querying the right bucket that is in the stack? 

I tried even adding a second lambda with S3 trigger to the same bucket in the stack and see both notifications.

**Comment by omersi** [comment]
No. 
the notification is an existing one for another lambda.

**Comment by jfuss** [comment]
@omersi Sorry I am a little lost on the problem now. 

Can you give me exact steps to reproduce the problem you are seeing? I have attempted this but from what I can gather, your setup is different than what you provided. It's hard to dig into this with the information you have provided, since I haven't been able to repo at all. Which indicates to me, you are doing something different. Otherwise, I am not sure how you would get a different result from the example I gave that was based on your original post.

The only other thing I can think of going on here, is something is wrong with S3 and would then be a service issue with them that AWS Support should be able to help you with.

**Comment by omersi** [comment]
I'll start from the beginning:

1. I have a trigger set on the desired bucket with a different path to a different lambda (`old lambda`).
2. I tried to create a `new lambda` with a trigger to a different path.
3. the lambda is created, the trigger isn't.

**Comment by jfuss** [comment]
@omersi This trigger was adding in CFN? Both for "old" and "new" lambdas? Is the bucket created in the CFN stack, the "old" and "new" lambda is in?

**Comment by omersi** [comment]
None of the "OLD" bucket, lambda, triggers were created using CFN. I can't tell if it was TF or manually.
I wanted to start using CFN/SAM for deploying new codes in an automated manner.

**Comment by jfuss** [comment]
@omersi Got it. That is really helpful.

So a little background, sorry if you know this already: 
For S3 triggers, SAM needs the Bucket to be in the same stack as the Function. This is because the S3 trigger is added to the S3 Bucket Notification Property (its not `AWS::Lambda::Permission`s like most of them are now). Without the S3 Bucket and Function being in the same template, SAM has no way to add the trigger. The SAM Transform should fail, but will verify this.

So if you are wanting to go down the CloudFormation/SAM route, here is what you will want to do:
1) [Import](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import.html) the S3 Bucket into a CFN stack
2) Once the Bucket is in the stack and the stack is deployed successfully, you can add the SAM Function and trigger into the stack. 

This should give you a way to add a trigger to this existing bucket. If you don't need this bucket and can use a new one, my example above: https://github.com/aws/serverless-application-model/issues/2113#issuecomment-892849620 would be the way to do that.

**Comment by omersi** [comment]
thanks for your assistance.

**Comment by jfuss** [comment]
@omersi No problem.

Closing as this is resolved.
